### ISSUE TITLE
Add package.json and publish on npm

### ISSUE THREAD

**Issue by cesarandreu** [ProLoser/Flexbox.less#15]
Please :D?

**Comment by ProLoser** [comment]
Is this project not completely broken? I have been pulling prs but I no longer review them. I have been worried that the code quality and organization might not be up to my personal standards and haven't even tested for breakage yet

**Comment by cesarandreu** [comment]
It's working fine, I've been using it for one of my projects.

**Comment by ProLoser** [comment]
Just a note, I was told this project isn't necessary if you use autoprefixer which has a similar philosophy

**Comment by cesarandreu** [comment]
Oh, really? I'm using webpack with less and autoprefixer actually. I didn't realize it would handle flexbox though. I'll try it out, thanks!

**Comment by ProLoser** [comment]
Yeah, I learned about it like a week or two ago. I just now checked the projects histories and confirmed my commits on this project started about a month or two before autoprefixer so at the time of creating this project autoprefixer didn't exist lol. I think I'm going to add a notice to the README, especially since I don't really maintain this anymore.

**Comment by cesarandreu** [comment]
I just tried it out and replaced all the mixins with normal css :D. Thanks for letting me know!
